[{{ pjpeerdefaults.inboundcontext }}]
exten => _X.,1,NoOp(Default inbound context)
  same => n,NoOp(AICONTEXT: ${AICONTEXT}, AIPROVIDER: ${AIPROVIDER}, AIOVERRIDE: ${AIOVERRIDE})
  same => n,Gosub(func-setvars,s,1)
  same => n,Goto(from-ai-agent,s,1)

[func-setvars]
exten => s,1,Set(AI_CONTEXT={{ pjpeerdefaults.aicontext }})
   same => n,Set(AI_PROVIDER={{ pjpeerdefaults.aiprovider }})
   same => n,Set(DEFAULT_AIOVERRIDE={{ pjpeerdefaults.allowaioverride }})
   same => n,ExecIf($[ "${DEFAULT_AIOVERRIDE}" != "True" ]?Return)
   same => n,ExecIf($[ "${AIOVERRIDE}" != "True" ]?Return) ; This is the one for the peer
   same => n,Set(H_AICONTEXT=${PJSIP_HEADER(read,X-AI-Context)})
   same => n,Set(H_AIPROVIDER=${PJSIP_HEADER(read,X-AI-Provider)})
   same => n,ExecIf($[ "${H_AICONTEXT}" != "" ]?Set(AI_CONTEXT=${H_AICONTEXT}))
   same => n,ExecIf($[ "${H_AIPROVIDER}" != "" ]?Set(AI_PROVIDER=${H_AIPROVIDER}))
   same => n,Return

; This is just debugging ignore
[from-pstn]
exten => 61770000000,1,NoOp(Hi)
    same => n,Ringing
    same => n,Wait(1)
    same => n,Playback(vm-from)
    same => n,Goto(from-ai-agent,s,1)
    same => n,Hangup


[from-ai-agent]
exten => s,1,NoOp(AI Voice Agent - Using Context ${AI_CONTEXT} and provider ${AI_PROVIDER})
exten => s,n,Stasis(asterisk-ai-voice-agent)
exten => s,n,Hangup()
