[general]

queue_log = no
rotatestrategy = rotate
exec_after_rotate=gzip -9 ${filename}.2

[logfiles]
debug.log => error,warning,notice,verbose,debug
trace.log => trace
security.log => security
; console => notice,warning,error
console => notice,warning,error,debug
messages.log => notice,warning,error
full.log => notice,warning,error,debug,verbose,dtmf,fax


