
.PHONY: git git-pull
git:
	@echo Hi git and git-pull

git-pull: $(AIDESTDIR)/.git/config
	cd $(AIDESTDIR); git pull; git checkout $(GITBRANCH)

$(AIDESTDIR)/.git/config:
	@mkdir -p $(AIDESTDIR)
	git clone $(GITREPO) $(AIDESTDIR)
