VIMFIXED=/tmp/.vimfixed

.PHONY: fixvim
# Comment out (") any lines that enable mouse overrides
fixvim $(VIMFIXED): | /usr/bin/vim
	@sed -i 's/ set mouse=/"set mouse=/' /usr/share/vim/*/defaults*
	@touch $(VIMFIXED)
	@echo Stopped vim from stealing the mouse.

